[features]
seeds = false
skip-lint = false
[programs.localnet]
wisdom_of_the_crowd = "F4R832vNyeoCnxFAEwVkhRcapXiA3CsAyRvmwWHEByTt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/cuscak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
